## Configuration file for Jekyll & Schrift template

#
# Jekyll configuration
#

# Global
safe: false
url: http://domain.xyz/
source:      .
destination: ./_site
plugins:     ./_plugins

# Server
port: 4000
base-url: http://schoewilliam.github.io/Schrift/ # Important to have the links work (leave a trailing /)

# Build options
future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   date
auto_ids:    true

#
# Schrift template configuration
#

# Enter below your name or pseudo & a short description
#    | These don't appear on the website. They are used to set the <META>s
author: Your Name
description: A clean and minimalist Jekyll template. Designed for prose.
title: Schrift template  # Appears in the window title of the browser. Stands alone on the homepage, sits beside the post title on post pages.

# Enter below the headtitle of your weblog/website
#    | It appears on the main navigation bar. You use <span></span> to nicely fade out some part of it
maintitle: Schrift <span>for Jekyll</span>

# Enter below a short description that will sit next to your head title.
#    | {optional}
maindesc: <a href=https://github.com/Schoewilliam/Schrift><span class=oi data-glyph=fork></span> Fork me</a>

# Enter below the items of your main menu
#    | Keep it a small amount. It is designed for a small menu.
menus:
- text: Archive
  url: /archive
  openiconic: list
- text: some page
  url: /anotherpage.html
  openiconic: list-rich
- text: an About page
  url: /about.html
  openiconic: info
  
# Enter an invitation message
#    | It lies right beneath every post to invite your readers to react and comment
#    | {optional}
invitationmsg: If you have any feedback you would like me to read, please don't hesitate to send them over to <a href=mailto:you@domain.xyz>you@domain.xyz</a>.
